/*
 * Immich Muzei source module
 */

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

android {
    namespace 'dev.abdus.apps.immich'
    compileSdk libs.versions.compileSdk.get().toInteger()

    buildFeatures {
        buildConfig = true
        compose = true
    }

    defaultConfig {
        applicationId 'dev.abdus.apps.immich'
        minSdkVersion 23
        targetSdkVersion libs.versions.targetSdk.get()
        versionCode project.hasProperty('version.code') ? project.property('version.code').toInteger() : 1
        versionName project.hasProperty('version.name') ? project.property('version.name') : '1.0.0'
    }

    def keystorePropertiesFile = rootProject.file("keystore.properties")
    def keystoreProperties = new Properties()
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }

    def keystorePath = System.getenv("KEYSTORE_FILE") ?: keystoreProperties['storeFile'] ?: project.findProperty("KEYSTORE_FILE")

    signingConfigs {
        if (keystorePath) {
            release {
                storeFile file(keystorePath)
                storePassword System.getenv("KEYSTORE_PASSWORD") ?: keystoreProperties['storePassword'] ?: project.findProperty("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS") ?: keystoreProperties['keyAlias'] ?: project.findProperty("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD") ?: keystoreProperties['keyPassword'] ?: project.findProperty("KEY_PASSWORD")
            }
            debug {
                storeFile file(keystorePath)
                storePassword System.getenv("KEYSTORE_PASSWORD") ?: keystoreProperties['storePassword'] ?: project.findProperty("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS") ?: keystoreProperties['keyAlias'] ?: project.findProperty("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD") ?: keystoreProperties['keyPassword'] ?: project.findProperty("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (keystorePath) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            if (keystorePath) {
                signingConfig signingConfigs.debug
            }
        }
    }

    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.compose.get()
    }

    kotlinOptions {
        jvmTarget = '11'
        freeCompilerArgs += [
            '-Xjvm-default=all'
        ]
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
        coreLibraryDesugaringEnabled = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation "com.squareup.okhttp3:mockwebserver:${libs.versions.okhttp.get()}"
    implementation libs.muzei.api
    implementation libs.activity
    implementation libs.core
    implementation platform(libs.compose.bom)
    implementation libs.compose.material3
    implementation libs.compose.icons
    implementation libs.compose.ui.tooling.preview
    debugImplementation libs.compose.ui.tooling.runtime
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.runtime
    implementation libs.lifecycle.livedata
    implementation libs.coroutines.android
    implementation libs.retrofit.core
    implementation libs.okhttp.core
    implementation libs.okhttp.logging
    implementation libs.coil.compose
    implementation libs.coil.okhttp
    implementation libs.kotlinx.serialization.json
    implementation libs.retrofit.kotlinx.serialization

    coreLibraryDesugaring libs.desugar.jdk.libs
}
